version: "3.8"
services:

  rpgdb:
    container_name: rpgdb
    hostname: rpgdb
    restart: always
    image: postgres:14.1-bullseye
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${ENV_POSTGRES_DB}
      - POSTGRES_USER=${ENV_POSTGRES_USER}
      - POSTGRES_PASSWORD=${ENV_POSTGRES_PASSWORD}

  rpgapp:
    container_name: rpgapp
    hostname: rpgapp
    restart: always
    build:
      context: /home/rjhadmin/tstsrv/rpg
      dockerfile: Dockerfile
    command: python rpg/manage.py runserver 0.0.0.0:8200
    volumes:
      - .:/code
    depends_on:
      - rpgdbdb
    ports:
      - 8200:8200
    labels:
      - traefik.http.routers.rpg.rule=Host(`rpg.${DOMAIN}`)
      - traefik.http.routers.rpg.entrypoints=https
      - traefik.http.routers.rpg.tls=true
      - traefik.http.routers.rpg.tls.certresolver=${CERT_RESOLVER}
