version: "3.8"
services:

  rpgdb:
    container_name: rpgdb
    hostname: rpgdb
    restart: always
    image: postgres:14.1-bullseye
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${ENV_POSTGRES_DB}
      - POSTGRES_USER=${ENV_POSTGRES_USER}
      - POSTGRES_PASSWORD=${ENV_POSTGRES_PASSWORD}

  rpgapp:
    container_name: rpgapp
    hostname: rpgapp
    restart: always
    build:
      context: .
      dockerfile: local-dev-Dockerfile
    command: python rpg/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    depends_on:
      - rpgdb
    ports:
      - 8000:8000
