version: "3.7"
services:

  db:
    image: postgres:14.1-bullseye
    volumes: 
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${ENV_POSTGRES_DB}
      - POSTGRES_USER=${ENV_POSTGRES_USER}
      - POSTGRES_PASSWORD=${ENV_POSTGRES_PASSWORD}

  rpg:
    build: 
      context: .
      dockerfile: local-win-Dockerfile
    command: python rpg/manage.py runserver localhost:8000
    volumes:
      - .:/code
    depends_on:
      - db
    ports:
      - 8000:8000

