version: "3.9"


services:


  database:
    image: mysql:8.0
    container_name: dsapi_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 23131001
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    security_opt:
     - seccomp:unconfined
    volumes:
     - ./db-dump:/docker-entrypoint-initdb.d
    ports:
    - "3306:3306"
  api:
    build: ./DeskShareApi
    ports:
      - "80:80"
    links:
      - database
 
